"""add col

Revision ID: 1cbdabdd4c3f
Revises: ddcfa55362f2
Create Date: 2025-06-05 08:32:43.640333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cbdabdd4c3f'
down_revision: Union[str, None] = 'ddcfa55362f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barangay', sa.Column('muni_parent_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_barangay_muni_parent_id'), 'barangay', ['muni_parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_barangay_muni_parent_id'), table_name='barangay')
    op.drop_column('barangay', 'muni_parent_id')
    # ### end Alembic commands ###
