"""delete col

Revision ID: ce366d4f859a
Revises: d87840de74f4
Create Date: 2025-06-05 15:57:30.419563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce366d4f859a'
down_revision: Union[str, None] = 'd87840de74f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_barangay_muni_parent_id'), table_name='barangay')
    op.drop_column('barangay', 'muni_parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barangay', sa.Column('muni_parent_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_barangay_muni_parent_id'), 'barangay', ['muni_parent_id'], unique=False)
    # ### end Alembic commands ###
