"""ondeletecascade

Revision ID: d87840de74f4
Revises: 1cbdabdd4c3f
Create Date: 2025-06-05 08:36:38.308560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd87840de74f4'
down_revision: Union[str, None] = '1cbdabdd4c3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('city_prov_id_fkey'), 'city', type_='foreignkey')
    op.drop_constraint(op.f('city_region_id_fkey'), 'city', type_='foreignkey')
    op.create_foreign_key(None, 'city', 'regions', ['region_id'], ['id'], ondelete='Cascade')
    op.create_foreign_key(None, 'city', 'province', ['prov_id'], ['id'], ondelete='Cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'city', type_='foreignkey')
    op.drop_constraint(None, 'city', type_='foreignkey')
    op.create_foreign_key(op.f('city_region_id_fkey'), 'city', 'regions', ['region_id'], ['id'])
    op.create_foreign_key(op.f('city_prov_id_fkey'), 'city', 'province', ['prov_id'], ['id'])
    # ### end Alembic commands ###
