"""create tb

Revision ID: ddcfa55362f2
Revises: 
Create Date: 2025-06-04 13:52:34.224801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddcfa55362f2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('region_name', sa.String(), nullable=True),
    sa.Column('region_code', sa.String(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('island_groups', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regions_id'), 'regions', ['id'], unique=False)
    op.create_index(op.f('ix_regions_region_code'), 'regions', ['region_code'], unique=False)
    op.create_index(op.f('ix_regions_region_name'), 'regions', ['region_name'], unique=False)
    op.create_table('province',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('region_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_province_id'), 'province', ['id'], unique=False)
    op.create_index(op.f('ix_province_name'), 'province', ['name'], unique=False)
    op.create_table('city',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prov_id', sa.String(), nullable=True),
    sa.Column('region_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prov_id'], ['province.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_city_id'), 'city', ['id'], unique=False)
    op.create_index(op.f('ix_city_name'), 'city', ['name'], unique=False)
    op.create_table('municipalities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prov_id', sa.String(), nullable=True),
    sa.Column('city_id', sa.String(), nullable=True),
    sa.Column('region_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['prov_id'], ['province.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_municipalities_id'), 'municipalities', ['id'], unique=False)
    op.create_index(op.f('ix_municipalities_name'), 'municipalities', ['name'], unique=False)
    op.create_table('barangay',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('city_id', sa.String(), nullable=True),
    sa.Column('municipalities_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['municipalities_id'], ['municipalities.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barangay_id'), 'barangay', ['id'], unique=False)
    op.create_index(op.f('ix_barangay_name'), 'barangay', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_barangay_name'), table_name='barangay')
    op.drop_index(op.f('ix_barangay_id'), table_name='barangay')
    op.drop_table('barangay')
    op.drop_index(op.f('ix_municipalities_name'), table_name='municipalities')
    op.drop_index(op.f('ix_municipalities_id'), table_name='municipalities')
    op.drop_table('municipalities')
    op.drop_index(op.f('ix_city_name'), table_name='city')
    op.drop_index(op.f('ix_city_id'), table_name='city')
    op.drop_table('city')
    op.drop_index(op.f('ix_province_name'), table_name='province')
    op.drop_index(op.f('ix_province_id'), table_name='province')
    op.drop_table('province')
    op.drop_index(op.f('ix_regions_region_name'), table_name='regions')
    op.drop_index(op.f('ix_regions_region_code'), table_name='regions')
    op.drop_index(op.f('ix_regions_id'), table_name='regions')
    op.drop_table('regions')
    # ### end Alembic commands ###
